name: paragonik
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.3+3

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_localization: ^0.3.3
  flutter_spinkit: ^5.2.2
  go_router: ^16.2.4
  google_mlkit_text_recognition: ^0.15.0
  image: ^4.5.4
  image_picker: ^1.2.0
  intl: ^0.20.2
  path: ^1.9.1
  path_provider: ^2.1.5
  photo_view: ^0.15.0
  provider: ^6.1.5+1
  sqflite: ^2.4.2
  uuid: ^4.5.1
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.3
  camera: ^0.11.3
  csv: ^6.0.0
  share_plus: ^12.0.1
  flutter_image_compress: ^2.4.0
  device_info_plus: ^12.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"
  adaptive_icon_background: "#673AB7"
  adaptive_icon_foreground: "assets/images/logo.png"

flutter_native_splash:
  color: "#673AB7"
  color_dark: "#673AB7"
  image: assets/images/splash_logo.png

  android_12:
    color: "#673AB7"
    color_dark: "#673AB7"
    image: assets/images/splash_logo.png
